services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.8
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    ports:
      - "9092:9092"
      - "29092:29092"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  osrm:
    image: osrm/osrm-backend:latest
    volumes:
      - ./osrm:/data
    ports:
      - "5000:5000"
    command: ["osrm-routed","--algorithm","mld","/data/graph.osrm"]

  traffic_processor:
    build:
      context: ../backend/traffic_processor
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BOOTSTRAP=localhost:29092
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

  crowdsourcing:
    build:
      context: ../backend/crowdsourcing
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=aimap
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"

  ai_ml_service:
    build:
      context: ../backend/ai_ml_service
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8002:8002"
